### PR TITLE
CRUD operations for User account creation

### LINKED ISSUE #15: Add CRUD operations for User table

### PR DESCRIPTION
**Pull request by yaaacii**
# [USE_ID] | [CRUD operations for User account creation]
> Team member: Cicelia Siu
> Use Case ID: 

Fixes #15 

## Expected Behavior
POST:/ should add form data into db
GET:/ should get all data from db
GET:/id should get data from db.id (given the id)
PUT:/id should update data from form data into db.id (given the id)

### - Usage 
1. Pull and try using Postman API using the above command

### - Considerations [optional]
Extra cases to consider 
1. Birthday formatting is incomplete
2. Profile picture is incomplete
3. Any other constraints I should add, let me know.

### - Evidence/Logs
Please include any relevant log snippets or images to support issue.
Screen Shot 2023-03-20 at 14 43 25
Screen Shot 2023-03-20 at 14 43 50

Screen Shot 2023-03-20 at 14 44 31
Screen Shot 2023-03-20 at 14 45 32

### CODE REVIEW

**Comment by edwardsung4217** [comment]
In insertUser.go
func main() {
	insert("yaacii", "ci@gmail.com", "siu", "2020-07-17", "Cicelia", "Siu")
}
was this meant for testing purposes?

**Comment by yaaacii** [comment]
Oh that file can be deleted. It was used for testing something eleeThank you,Cicelia SiuOn Mar 22, 2023, at 10:29 AM, Edward Sung ***@***.***> wrote:﻿
In insertUser.go
func main() {
insert("yaacii", ***@***.***", "siu", "2020-07-17", "Cicelia", "Siu")
}
was this meant for testing purposes?

**Comment by edwardsung4217** [comment]
> Oh that file can be deleted. It was used for testing something eleeThank you,Cicelia SiuOn Mar 22, 2023, at 10:29 AM, Edward Sung ***@***.***> wrote:﻿ In insertUser.go func main() { insert("yaacii", ***@***.***", "siu", "2020-07-17", "Cicelia", "Siu") } was this meant for testing purposes? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Otherwise looks good, please just remove all testing code such as that and update. I will approve afterwards. Thank you!

**Review by edwardsung4217 — CHANGES_REQUESTED** [review]
Looks good to me, just remove testing code and update. Thank you

**Review by lazeroffmichael — APPROVED** [review]
Looks good. We will have to refactor to the new scheme and include tests, but this has everything it needs.

**Review by edwardsung4217 — APPROVED** [review]
Look good. Will approve for now just to get it into the branch but refactor for unit testing at a later date. Thank you!

**Pull request merged**
