### PR TITLE
45 crud operations for events

### LINKED ISSUE #45: CRUD operations for events

### PR DESCRIPTION
**Pull request by dzeleniak**
Fixes #45 

## Expected Behavior
This contribution adds the ability to Create, Fetch, Update and Delete events from the database using HTTP requests.

### CODE REVIEW

**Review by lazeroffmichael — APPROVED** [review]
Event operations look good to go. We will wait to merge this until the other PR's are merged so that all of our tests do not get messed up.

**Review by edwardsung4217 — CHANGES_REQUESTED** [review]
Screen Shot 2023-04-19 at 7 58 28 PM
Screen Shot 2023-04-19 at 7 58 21 PM

I was looking through the events tab on the front end part and noticed that what they had for events is a lot more than what your api's return. Please update your code so that it returns what frontend has or request them to match your changes. Either one works

**Comment by dzeleniak** [comment]
Gotcha - I'll get to work on that. Should be relatively quick to fix.

**Comment by yaaacii** [comment]
Does this PR have the option for users to sign up for events as well?

**Review by dzeleniak — COMMENTED** [review]
Updated code to accomodate changes

**Review by edwardsung4217 — APPROVED** [review]
Looks good now. Thank you for the changes!

**Pull request merged**
