### PR TITLE
update unit testing users

### PR DESCRIPTION
**Pull request by yaaacii**
# [UC1.2-1.3] | Update unit test for users
> Team member: Cicelia Siu
> Use Case ID: 1.2-1.3

TEMPORARY!!!!

Fixes #[Issue]

## Expected Behavior
All tests should pass with 16% controller, 60% repository and 68% service coverage

## Issue
Unit tests

### - Usage 
1. go test ./... -cover -v

### - Considerations [optional]
Extra cases to consider 
1. May need to include Update Test

### - Evidence/Logs
Please include any relevant log snippets or images to support issue.

Screen Shot 2023-04-18 at 15 08 05

### CODE REVIEW

**Review by Rahgid — CHANGES_REQUESTED** [review]
I added a commit with the fix for your other test. Just write a quick description of what this PR does and I'll approve.

**Comment by Rahgid** [comment]
Can you remove the temporary stuff at the top? Also mention that this PR fixes some broken tests & adds some mocks.

**Review by Rahgid — APPROVED** [review]
Can you remove the temporary stuff at the top? Also mention that this PR fixes some broken tests & adds some mocks. 

It’s just some nit. description stuff, I’ll grant approval though.

**Review by lazeroffmichael — APPROVED** [review]
Two login controller tests were failing, but I went ahead and fixed them. All tests should be passing now.

image

**Pull request merged**
