### PR TITLE
58 CRUD friends w/o unit testing

### PR DESCRIPTION
**Pull request by yaaacii**
# [58] | (UC4.5.1 and UC4.5.2) Adding/Removing Friends
> Team member: Cicelia Siu
> Use Case ID:

Fixes #[58]

## Expected Behavior
CRUD operations for friends

### - Usage 
1. localhost:8000/friends
2. post "/" : with FriendOneHandle and FriendTwoHandle in body - creates the friends request with pending status
3. delete "/:id"  - deletes the request based on id (used when rejecting or removing friend)
4. one "/:id"  and all"/" - getting friend object

### - Evidence/Logs
Screen Shot 2023-04-21 at 16 38 56
Screen Shot 2023-04-21 at 16 38 10

Screen Shot 2023-04-21 at 16 38 35

Screen Shot 2023-04-21 at 16 38 40
Screen Shot 2023-04-21 at 16 52 55
Screen Shot 2023-04-21 at 16 38 49

### CODE REVIEW

**Review by edwardsung4217 — APPROVED** [review]
For the friend models I believe that we have moved away from adding "id" into it since gorm already adds it for you so its redundant code. I'll approve since there's really nothing wrong with it but just take it out before your merge. Thank you

**Comment by dzeleniak** [comment]
Hey Cici, 

The structure in general looks good, but like edward said, you should remove the ID from the model as the gorm.Model key will create that as well as other necessary fields. 

Also please update the code to remove some of the conflict messages. There are large sections duplicated in both files because of this.

**Review by lazeroffmichael — APPROVED** [review]
The model looks good now, so this should be good to go. I'll write the tests, thank you!

**Review by Rahgid — APPROVED** [review]
I think this looks good aside from Michael's upcoming PR for the unit tests. Ideally, I think we would target users by their user ID and only their user ID because it's guaranteed to always be the same. Obviously "Handle" is a unique field, but if we ever decide to implement anything that allows users to change their handle, this will become something very annoying to deal with.

That being said, I'm still fine with this change, but we should be aware of that for the future in case we do make that decision.

**Pull request merged**
